# -*- coding: utf-8 -*-
"""Capítulo_03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PEdgfXpr7XHM1oO9NgncbpLfV62BTjGp
"""

pessoa = {
    "nome": "Marcelo",
    "endereco": "Rua das Flores, 74",
    "idade": 18
}
print(pessoa)
print(pessoa['idade'])

lista = ['Marcelo', 'Maria', 'José', 'João']
print(lista)
print(lista[0])
print(lista[-1])
print(lista[2:4])
print(lista[:2])
lista[0] = 'Rodrigo'
print(lista)
print('O tamanho da lista é {}.'.format(len(lista)))

lista = ['Marcelo', 'Maria', 'José', 'João']
lista.append('Joana')
lista_copia = lista.copy()
lista_copia[0] = 'Rodrigo'
print(lista)
print(lista_copia)

lista = ['Marcelo', 'Maria', 'José', 'João']
lista.insert(2, 'Joana')
print(lista)
lista.remove('Maria')
print(lista)

lista = ['Marcelo', 'Maria', 'José', 'João']
nome_retirado = lista.pop(2)
print(lista)
print(nome_retirado)

lista = ['Marcelo', 'Maria', 'José', 'João']
if 'Marcelo' in lista:
  print('O Marcelo está na lista!')
else:
  print('O Marcelo não está na lista!')

tupla = ('Marcelo', 'Maria', 'José', 'João', "Joana D'arc")
print(tupla)
print('Marcelo' in tupla)

lista_pessoas = []
lista_pessoas.append({
    "nome": "Marcelo",
    "endereco": "Rua das Flores, 74",
    "idade": 18
})

lista_pessoas.append({
    "nome": "Marcelo",
    "endereco": "Rua das Canárias, 20",
    "idade": 50
})

lista_pessoas.append({
    "nome": "Sandra",
    "endereco": "Rua das Pedras Preciosas, 500",
    "idade": 30
})
print(lista_pessoas)

from getpass import getpass

senha_correta = False
senha = ""
tentativas = 3
while (not senha_correta) and (tentativas > 0):
  senha = getpass("Digite a sua senha: ")
  senha_correta = senha == 'secreto'
  if (not senha_correta):
    print("A senha não está correta!")
    tentativas -= 1
    print("Vc tem mais {} tentativas.".format(tentativas))
if tentativas > 0:
 print("Parabéns! Vc acertou a senha!")
else:
  print("Acesso bloqueado!")

lista_pessoas = []
lista_pessoas.append({
    "id": 1,
    "nome": "Marcelo",
    "endereco": "Rua das Flores, 74",
    "idade": 18,
    "salário": 1000.00,
})

lista_pessoas.append({
    "id": 2,
    "nome": "Marcelo",
    "endereco": "Rua das Canárias, 20",
    "idade": 50,
    "salário": 10000.00,
})

lista_pessoas.append({
    "id": 3,
    "nome": "Sandra",
    "endereco": "Rua das Pedras Preciosas, 500",
    "idade": 30,
    "salário": 5000.20,
})

print("Mostrando pessoas com salário maior que R$1000")
for pessoa in lista_pessoas:
  if (pessoa['salário'] > 1000):
   print('A pessoa de id {}, tem o nome {}.'.format(pessoa['id'], pessoa['nome']))

# Mostra números de 1 a 10

for numero in range(1, 11):
  print("Número: {}".format(numero))

# Mostra números pares de 1 a 10

for numero in range(2, 11, 2):
  print("Número: {} é par.".format(numero))

from getpass import getpass, getuser

senha = getpass("Digite sua senha: ")
usuario = getuser()
print(usuario)

# Digitar item da compra e a quantidade comprada
# Verificar o valor total
# Quando encerrar a compra, dou o valor total da compra

produtos = ["Hamburguer", "Batatas fritas", "Combo", "Refrigerante"]
precos = [15, 10.5, 20, 5]
itens_comprados = []

valor_compra = 0
item_compra = int(input("Qual o identificador do item da compra? "))
itens_comprados.append(produtos[item_compra])

informacao = input("Qual a quantidade consumida? ")
while (not informacao.isdigit()):
  informacao = input("A quantidade consumida deve ser um número inteiro. Digite novamente: ")
quantidade = int(informacao)

while item_compra != -1:
  valor_compra = valor_compra + (precos [item_compra] * quantidade)
  item_compra = int(input("Qual o identificador da compra? "))
  if (item_compra == -1):
    break
  itens_comprados.append(produtos[item_compra])
  informacao = input("Qual a quantidade consumida? ")
  while (not informacao.isdigit()):
    informacao = input("A quantidade consumida deve ser um número inteiro. Digite novamente: ")
  quantidade = int(informacao)

print("**** Relatório da compra. ****")
for item in itens_comprados:
  print("Comprado: {}.".format(item))
print("*********************************")
print("Total da compra R${}.".format(valor_compra))